### ISSUE TITLE
[Feature] Valorization of the "Tool output" field of the memory chain prompt with the string returned by a tool

### ISSUE THREAD

**Issue by piust** [cheshire-cat-ai/core#555] opened 2023-11-09 14:29 UTC
When the observations returned by the custom tools is passed to the _Memory Chain_ step they are interpreted by the LLM and can change a lot.
This is not a problem most of the time, but it is a problem when the answer **is non interpretable**.
If the tool returns a meaningless word, like a username or a nickname, the LLM may not be able to comprehend what it is and discard the tool response.
For example the tool can answer something like "The username is piust0000", but this can be transformed in "piust0000" when setting the **Tool output** field in the memory chain prompt. "piust0000" is not a word so the LLM cannot understand its meaning and answers that he doesn't know the username or, sometimes, invents a new one.
I know that you can skip the memory chain completely by setting "return_direct=True" in the tool decorator, but sometimes one want to make the cat answer as it's defined in the prompt prefix, like a pirate or a poet.
I suggest we implement a way to force the Agent to populate the **Tool output** field with the string returned by the tool itself.

Maybe we can create new tool decorator parameter that, when set to True, force this behaviour.

**I talked about this idea on Discord some days ago, but I totally forgot to put it here.
Sorry for the delay.**

**Comment by Pingdred** [comment] 2023-11-09 14:52
Could you explain to me what in your opinion is the cause of the transformation of the sentence "The username is piust0000" into "piust0000".  If a tool is not return direct its output should be inserted into the Memory chain as it returns it

**Comment by piust** [comment] 2023-11-09 16:28
I pasted here an example. Here the tool answer is "The creator of issue 461 is zenimarc" but  at the bottom you can read that the  ## Tools output: field is zenimarc, not all the original tool output.
I suppose that the LLM interprets the tool output end extract the single word zenimarc as Final Answer.

```
cheshire_cat_core           | Question: who created issue 461?
cheshire_cat_core           |
cheshire_cat_core           | Action: get_creator
cheshire_cat_core           | Action Input: 461
cheshire_cat_core           | Observation: The creator of issue 461 is zenimarc.
cheshire_cat_core           |
cheshire_cat_core           |
cheshire_cat_core           | > Finished chain.
cheshire_cat_core           | Final Answer: zenimarc
cheshire_cat_core           |
cheshire_cat_core           | > Finished chain.
cheshire_cat_core           |
cheshire_cat_core           |
cheshire_cat_core           | > Entering new LLMChain chain...
cheshire_cat_core           | Prompt after formatting:
cheshire_cat_core           | You are HAL9000, an intelligent AI that passes the Turing test.
cheshire_cat_core           | You are brilliant and talk like HAL9000 from 2001 A space Odyssey.
cheshire_cat_core           | You are linked to a github repository and your task is to answer generic questions about its issues.
cheshire_cat_core           | If you cannot find the requested information simply say that you don't have the answer.
cheshire_cat_core           | You must give more credits to the information in ## Tools output
cheshire_cat_core           | Don't give more information than requested by the human.
cheshire_cat_core           | You answer Human with a focus on the following context.
cheshire_cat_core           |
cheshire_cat_core           | # Context
cheshire_cat_core           |
cheshire_cat_core           |
cheshire_cat_core           |
cheshire_cat_core           | ## Context of documents containing relevant information:
. # Checklist: (extracted from doc_470.txt)n updatecause existing functionality to not work as expected)
cheshire_cat_core           |   - Issue Number: 479. Issue id: 1930614468. URL: https://github.com/cheshire-cat-ai/core/issues/479. Title: [PIZZA ORDER CHALLENGE] Make it easy to manage conversational forms from a plugin. Created by: pieroit. Creation date: 06 10 2023. Creation hour: 16:53. Close date: None (extracted from doc_479.txt)
. - [x] I have commented my code, particularly in hard-to-understand areas (extracted from doc_393.txt)
cheshire_cat_core           |
cheshire_cat_core           | ## Tools output:
cheshire_cat_core           | zenimarc
```

**Comment by pieroit** [comment] 2024-02-24 09:19
Thank you @piust for noticing this

The `final answer` ended up in the memory chain and not the tool output, because the tool agent is built like that in langchain

In the future we will get rid of the langchain agent for more custom chains.
For the moment I close this, I guess we cannot do much

**Closed** 2024-02-24 09:19 UTC
Labels: enhancement
