### ISSUE TITLE
[BUG] I think something is wrong with plugins

### ISSUE THREAD

**Issue by Roby91** [cheshire-cat-ai/core#401] opened 2023-08-06 15:08 UTC
I'm not able to "fire" any plugin.
I tried with different custom plugins (for example "poetic_sock_seller" from https://cheshirecat.ai/2023/06/17/write-your-first-plugin/) but they do not activate during conversation.
Even the default "get_the_time" plugin does not work (no expected answer) after asking "what time is it", "get the clock", etc.
In the console i do not see any "reasoning" about plugins between one conversation and another.

I'm running the last version of the cat (where can I find the version reference by the way?) with "Azure OpenAI Chat model" (gpt-35-turbo) as language model configured.
The language model is well configured because I can chat with the cat normally, the hooks are working (i can see the change in prompt from console) but i cannot make the tools work as I expect.

Moreover, when I add custom plugins I see disabled toggles on the bottom of the "delete" buttons, in Plugins section of Admin page. Is that normal or I miss something?

**Comment by zAlweNy26** [comment] 2023-08-06 15:10
The plugin toggle is disabled because the core functionality is still in develop branch, it will be enabled when it will be merged into main.

**Comment by Roby91** [comment] 2023-08-06 15:46
> The plugin toggle is disabled because the core functionality for that is still in develop branch, it will be enabled when it will be merged into main.

Ok thanks to let it me know!

**Comment by cristianorevil** [comment] 2023-08-07 05:26
@pieroit on develop branch (latest commit) i have same issue: custom tools and hooks defined into plugins are not executed anymore, but plugins are correctly showed in the admin section.

**Comment by pieroit** [comment] 2023-08-07 05:37
@Roby91 @cristianorevil can you try to:
- stop the cat
- delete core/metadata.json
- restart

**Comment by cristianorevil** [comment] 2023-08-07 05:41
> @Roby91 @cristianorevil can you try to:
> 
> * stop the cat
> * delete core/metadata.json
> * restart

I have tried but the problem still remain (I have deleted metadata json, start the cat and reconfigured LLM (Azure OpenAI GPT-4)

**Comment by pieroit** [comment] 2023-08-07 05:55
Do hooks work? Or is it related just to tools?

**Comment by cristianorevil** [comment] 2023-08-07 06:03
No also hooks not working :-(

**Comment by pieroit** [comment] 2023-08-07 06:08
Ok, then remove the plugins and reinstall them again

Should be because plugins are activated in the moment they are installed (via admin or via folder

If plugin were there before updating the code, the cat assumes he has to keep them deactivated - unless you switch them on in the admin

This bug will go away as you will have a switch on/off button for plugins in the admin. So of for any reason they are switched off, they can be reactivated

Let me know please

**Comment by cristianorevil** [comment] 2023-08-07 06:34
I have tried to remove plugin and re-add via folder or zip but the issue persist:

![Screenshot 2023-08-07 alle 08 31 50](https://github.com/cheshire-cat-ai/core/assets/49713716/c5631759-f3ae-4869-988e-61adcdb87f93)

**Comment by Roby91** [comment] 2023-08-07 19:07
@pieroit I tried cleaning up core/metadata.json and even deleting the whole project and cloning it again: i get the same behaviour.
I tried starting the cat without any plugin and adding them after (I can see the automatic reload from terminal) and starting the cat with plugins alredy present: it doesn't metter.
I think the hooks are working because I can see a different prompt (see the screenshoot)

![Screenshot 2023-08-07 20 59 48](https://github.com/cheshire-cat-ai/core/assets/12767821/906f7f46-c6a7-4691-a7bc-874893d0843f)

**Comment by Roby91** [comment] 2023-08-07 19:16
Even without any "custom plugin" installed I'm not able to get the time from "core\cat\mad_hatter\core_plugin\tools.py" default plugin but only generic answers from the language model.

![Screenshot 2023-08-07 21 11 48](https://github.com/cheshire-cat-ai/core/assets/12767821/2d11b732-e53c-43a8-a5db-4a0f6b9dbb3b)

**Comment by pieroit** [comment] 2023-08-07 19:24
@Roby91 can confirm the problem is plugins being deactivated; Since the toggle button in the admin is not yet implemented, activate plugins manually in `localhost:1865/docs`, endpoint `plugins/toggle`

**Comment by zAlweNy26** [comment] 2023-08-07 19:27
If you want to use the core develop branch, you should also download separately the develop branch of the admin

**Closed** 2023-08-21 10:30 UTC
Labels: bug
