### ISSUE TITLE
1.4.5/1.5.1 problems using Azure OAI

### ISSUE THREAD

**Issue by olafgeibig** [cheshire-cat-ai/core#745] opened 2024-03-11 21:01 UTC
Upgrading from 1.4.5 to 1.5.1 caused problems to my production system.

**Trouble with 1.5.1**
It's impossible now to configure Azure OAI correctly. It never works and always says I have no LLM. 

**Trouble with 1.4.5**
Suddenly gpt-4-1106-preview became unbearably slow (in region Sweden central). Probably they are phasing out the preview versions. Therefore I updated my model deployment to vision-preview. The problem is that the generation stops after that the first line is written to the chat. In Azure OAI playground the model generates normally. Therefore I upgraded to 1.5.1. Subsequently restarting the cat resulted in errors with the LLM config.

**Comment by pieroit** [comment] 2024-03-11 21:04
@olafgeibig let's try to fix.

What's the exact error Azure is putting out? Also try to delete cat/data/metadata json, Azure changed the parameters names so that may be the reason

P.S. always back up your volums and vector db before updating. We are getting stable but we need time ;)

**Comment by olafgeibig** [comment] 2024-03-11 21:20
At least I could restore the data from a local backup :) 

Okay, let's look forward and fix the situation with 1.5.1.

I do docker-compose up, everything starts up in a fresh directory. I configure the LLM like so
![Screenshot 2024-03-11 at 22 19 01](https://github.com/cheshire-cat-ai/core/assets/295644/8c9678fb-a182-4eb6-8b7a-816620b9e304)
The I hit save and it gets stuck in a animation forever
![Screenshot 2024-03-11 at 22 16 43](https://github.com/cheshire-cat-ai/core/assets/295644/aea229cb-76ae-42ec-9083-04b27951a4eb)
Log output:
```
cheshire_cat_core-vibe  | INFO:     172.22.0.1:34898 - "PUT /llm/settings/LLMAzureChatOpenAIConfig HTTP/1.1" 500 Internal Server Error
cheshire_cat_core-vibe  | ERROR:    Exception in ASGI application
cheshire_cat_core-vibe  | Traceback (most recent call last):
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
cheshire_cat_core-vibe  |     result = await app(  # type: ignore[func-returns-value]
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
cheshire_cat_core-vibe  |     return await self.app(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
cheshire_cat_core-vibe  |     await super().__call__(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
cheshire_cat_core-vibe  |     await self.middleware_stack(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
cheshire_cat_core-vibe  |     raise exc
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
cheshire_cat_core-vibe  |     await self.app(scope, receive, _send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
cheshire_cat_core-vibe  |     await self.simple_response(scope, receive, send, request_headers=headers)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
cheshire_cat_core-vibe  |     raise exc
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
cheshire_cat_core-vibe  |     await self.app(scope, receive, sender)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
cheshire_cat_core-vibe  |     raise e
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
cheshire_cat_core-vibe  |     await route.handle(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
cheshire_cat_core-vibe  |     response = await func(request)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
cheshire_cat_core-vibe  |     raw_response = await run_endpoint_function(
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
cheshire_cat_core-vibe  |     return await run_in_threadpool(dependant.call, **values)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
cheshire_cat_core-vibe  |     return await anyio.to_thread.run_sync(func, *args)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
cheshire_cat_core-vibe  |     return await get_asynclib().run_sync_in_worker_thread(
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
cheshire_cat_core-vibe  |     return await future
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
cheshire_cat_core-vibe  |     result = context.run(func, *args)
cheshire_cat_core-vibe  |   File "/app/cat/routes/llm.py", line 122, in upsert_llm_setting
cheshire_cat_core-vibe  |     ccat.load_natural_language()
cheshire_cat_core-vibe  |   File "/app/cat/looking_glass/cheshire_cat.py", line 100, in load_natural_language
cheshire_cat_core-vibe  |     self.embedder = self.load_language_embedder()
cheshire_cat_core-vibe  |   File "/app/cat/looking_glass/cheshire_cat.py", line 186, in load_language_embedder
cheshire_cat_core-vibe  |     embedder = embedders.EmbedderAzureOpenAIConfig.get_embedder_from_config(
cheshire_cat_core-vibe  |   File "/app/cat/factory/embedder.py", line 34, in get_embedder_from_config
cheshire_cat_core-vibe  |     return cls._pyclass.default(**config)
cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
cheshire_cat_core-vibe  |     raise validation_error
cheshire_cat_core-vibe  | pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
cheshire_cat_core-vibe  | __root__
cheshire_cat_core-vibe  |   Must provide one of the `base_url` or `azure_endpoint` arguments, or the `AZURE_OPENAI_ENDPOINT` environment variable (type=value_error)
cheshire_cat_core-vibe  | INFO:     172.22.0.1:47460 - "GET /admin/settings HTTP/1.1" 200 OK
```

**Comment by valentimarco** [comment] 2024-03-11 21:28
> At least I could restore the data from a local backup :)
> 
> Okay, let's look forward and fix the situation with 1.5.1.
> 
> I do docker-compose up, everything starts up in a fresh directory. I configure the LLM like so ![Screenshot 2024-03-11 at 22 19 01](https://private-user-images.githubusercontent.com/295644/311870400-8c9678fb-a182-4eb6-8b7a-816620b9e304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTIzMDUsIm5iZiI6MTcxMDE5MjAwNSwicGF0aCI6Ii8yOTU2NDQvMzExODcwNDAwLThjOTY3OGZiLWExODItNGViNi04YjdhLTgxNjYyMGI5ZTMwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTc4MDMzYTBkMGQ5NTFiNWE4MjhjNTQyOTQ5MWQ3ZDk3NjA4ZmZmNTg4MTAyNTcyYzg0NTYxMDY2NGZmZGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TpKo3tHhkxLdaY_5esMz_KPo1sY0rSEdcJQtpOH4e9o) The I hit save and it gets stuck in a animation forever ![Screenshot 2024-03-11 at 22 16 43](https://private-user-images.githubusercontent.com/295644/311870501-aea229cb-76ae-42ec-9083-04b27951a4eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTIzMDUsIm5iZiI6MTcxMDE5MjAwNSwicGF0aCI6Ii8yOTU2NDQvMzExODcwNTAxLWFlYTIyOWNiLTc2YWUtNDJlYy05MDgzLTA0YjI3OTUxYTRlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTUzNmU0NGMwMTBiZTgxZTQ1ZTQ0NGY0ZTE0ZGIwMjQ5NmE3ZDkyZjRkNzRhZTM0OTAyZTY4NGM3NGNhY2U1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V9M-h5LFlLsXF901b4anGDrPqtbtwYZ_2u4rr5Dm5BQ) Log output:
> 
> ```
> cheshire_cat_core-vibe  | INFO:     172.22.0.1:34898 - "PUT /llm/settings/LLMAzureChatOpenAIConfig HTTP/1.1" 500 Internal Server Error
> cheshire_cat_core-vibe  | ERROR:    Exception in ASGI application
> cheshire_cat_core-vibe  | Traceback (most recent call last):
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
> cheshire_cat_core-vibe  |     result = await app(  # type: ignore[func-returns-value]
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> cheshire_cat_core-vibe  |     return await self.app(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
> cheshire_cat_core-vibe  |     await super().__call__(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
> cheshire_cat_core-vibe  |     await self.middleware_stack(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
> cheshire_cat_core-vibe  |     raise exc
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
> cheshire_cat_core-vibe  |     await self.app(scope, receive, _send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
> cheshire_cat_core-vibe  |     await self.simple_response(scope, receive, send, request_headers=headers)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
> cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
> cheshire_cat_core-vibe  |     raise exc
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
> cheshire_cat_core-vibe  |     await self.app(scope, receive, sender)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
> cheshire_cat_core-vibe  |     raise e
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
> cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
> cheshire_cat_core-vibe  |     await route.handle(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
> cheshire_cat_core-vibe  |     await self.app(scope, receive, send)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
> cheshire_cat_core-vibe  |     response = await func(request)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
> cheshire_cat_core-vibe  |     raw_response = await run_endpoint_function(
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
> cheshire_cat_core-vibe  |     return await run_in_threadpool(dependant.call, **values)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
> cheshire_cat_core-vibe  |     return await anyio.to_thread.run_sync(func, *args)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
> cheshire_cat_core-vibe  |     return await get_asynclib().run_sync_in_worker_thread(
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> cheshire_cat_core-vibe  |     return await future
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> cheshire_cat_core-vibe  |     result = context.run(func, *args)
> cheshire_cat_core-vibe  |   File "/app/cat/routes/llm.py", line 122, in upsert_llm_setting
> cheshire_cat_core-vibe  |     ccat.load_natural_language()
> cheshire_cat_core-vibe  |   File "/app/cat/looking_glass/cheshire_cat.py", line 100, in load_natural_language
> cheshire_cat_core-vibe  |     self.embedder = self.load_language_embedder()
> cheshire_cat_core-vibe  |   File "/app/cat/looking_glass/cheshire_cat.py", line 186, in load_language_embedder
> cheshire_cat_core-vibe  |     embedder = embedders.EmbedderAzureOpenAIConfig.get_embedder_from_config(
> cheshire_cat_core-vibe  |   File "/app/cat/factory/embedder.py", line 34, in get_embedder_from_config
> cheshire_cat_core-vibe  |     return cls._pyclass.default(**config)
> cheshire_cat_core-vibe  |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
> cheshire_cat_core-vibe  |     raise validation_error
> cheshire_cat_core-vibe  | pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
> cheshire_cat_core-vibe  | __root__
> cheshire_cat_core-vibe  |   Must provide one of the `base_url` or `azure_endpoint` arguments, or the `AZURE_OPENAI_ENDPOINT` environment variable (type=value_error)
> cheshire_cat_core-vibe  | INFO:     172.22.0.1:47460 - "GET /admin/settings HTTP/1.1" 200 OK
> ```

Did you try to reset the cache of the browser??

**Comment by olafgeibig** [comment] 2024-03-11 21:35
Deleting the cache did not change anything

**Comment by valentimarco** [comment] 2024-03-11 21:37
is the same error?

**Comment by olafgeibig** [comment] 2024-03-11 21:46
yes

**Comment by valentimarco** [comment] 2024-03-11 21:49
Ok, we Need more support @zioproto @cristianorevil

**Comment by olafgeibig** [comment] 2024-03-12 09:08
@zioproto sorry, I was in panic yesterday. Fixed the issue title and content.

**Comment by olafgeibig** [comment] 2024-03-12 09:14
Here is a metadata.json that was freshly generated by a new cat.

{"_default": {"1": {"name": "LLMAzureChatOpenAIConfig", "value": {"openai_api_key": "xxx", "model_name": "gpt-4", "azure_endpoint": "https://xxx.openai.azure.com", "openai_api_type": "azure", "openai_api_version": "2024-03-15-preview", "azure_deployment": "gpt-4", "streaming": true}, "category": "llm_factory", "setting_id": "550d644e-58df-43f2-a8f8-2e111a321ee2", "updated_at": 1710192973}, "2": {"name": "llm_selected", "value": {"name": "LLMAzureChatOpenAIConfig"}, "category": "llm", "setting_id": "683b0479-fb61-4b23-b0c0-805122a0a80f", "updated_at": 1710192973}}}

**Comment by olafgeibig** [comment] 2024-03-12 11:20
Okay, the above problem is caused by the API version that was specified which is not available for the vision-preview model. I replaced it with 2024-02-15-preview and then the cat use the Azure OAI API successful. Basically the bug is, that the API endpoint URL is not taken from the metadata.json field "azure_endpoint". Without setting the environment variable, the cat fails during startup.

The last real problem that remains is that the generated output is cut off after the first line:

```
{
cheshire_cat_core-vibe  |     "input": "Does pineapple belong on pizza?",
cheshire_cat_core-vibe  |     "episodic_memory": "## Context of things the Human said in the past: \n  - What's up? (4 minutes ago)\n  - What is Python? (2 minutes ago)\n  - Explain the reson of life (4 minutes ago)",
cheshire_cat_core-vibe  |     "declarative_memory": "",
cheshire_cat_core-vibe  |     "chat_history": "",
cheshire_cat_core-vibe  |     "tools_output": "",
cheshire_cat_core-vibe  |     "output": "Ah, the age-old question, as perplexing as a riddle from the",
cheshire_cat_core-vibe  |     "intermediate_steps": []
cheshire_cat_core-vibe  | }
```

**Comment by cristianorevil** [comment] 2024-03-12 13:51
Do you have also set the Embedder to use. Azure OpenAI? In my installation all works without settings environment variable. Check in metadata.json if you have set Embedder like this:

"3": {
      "name": "EmbedderAzureOpenAIConfig",
      "value": {
        "openai_api_key": "XXXXXXX",
        "model": "text-embedding-ada-002",
        "azure_endpoint": "https://xxxxxxx-swedencentral.openai.azure.com",
        "openai_api_type": "azure",
        "openai_api_version": "2024-02-15-preview",
        "deployment": "text-embedding-ada-002"
      },
      "category": "embedder_factory",
      "setting_id": "713de6bf-af6d-4077-87a1-5312a7a2c200",
      "updated_at": 1709885858
      
      The output cut off i think is an Azure problem, in this weeks there is some issue with Azure OpenaAI with gpt4

**Comment by pieroit** [comment] 2024-03-12 14:21
Thanks @cristianorevil 
@olafgeibig let us know if you fixed

**Comment by zioproto** [comment] 2024-03-12 14:21
I can reproduce on a greenfield installation. Not related to the upgrade from 1.4.5 to 1.51.

I believe the problem is in this block of code:
https://github.com/cheshire-cat-ai/core/blob/4c9fff02470ecd406a346652d035aa98ada71d58/core/cat/looking_glass/cheshire_cat.py#L184-L202

After PR https://github.com/cheshire-cat-ai/core/pull/715 I believe line 195 `openai_api_base` needs to be updated to `azure_endpoint`.

@cristianorevil

**Comment by zioproto** [comment] 2024-03-12 14:23
@cristianorevil do you use the web interface shipped with the cat for the configuration ?

I get:
```
cheshire_cat_core  | INFO:     192.168.65.1:23308 - "PUT /llm/settings/LLMAzureChatOpenAIConfig HTTP/1.1" 500 Internal Server Error
```

when saving the config, because from the web interface you cannot configre the LLM and the embedder at the same time

**Comment by zioproto** [comment] 2024-03-12 14:24
We also have an hardcoded `"openai_api_version": "2023-05-15", ` because of the old https://github.com/hwchase17/langchain/issues/4775  problem. This all code needs a refactory

**Comment by cristianorevil** [comment] 2024-03-12 14:27
@zioproto yes i was saved from web interface after created the PR. Anyway there is a change to do core/core/cat/looking_glass/cheshire_cat.py, and update the code beacuse with new version of the cat in log using Azure OpenAI i get this message:

LangChainDeprecationWarning: The class `langchain_community.chat_models.azure_openai.AzureChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import AzureChatOpenAI`.

**Comment by zioproto** [comment] 2024-03-12 14:28
@cristianorevil if you can point me to a working commit we can do a `git bisect` to identify the commit that broke it

**Comment by zioproto** [comment] 2024-03-12 14:43
I rolled back at `602ac8e` and I have the same problem. I supposed this worked only when using an existing configuration file ?

**Comment by cristianorevil** [comment] 2024-03-12 14:45
Probably and i don't have notice that....

**Comment by zioproto** [comment] 2024-03-12 15:39
I pushed a PR to fix partially the problem.

The real problem is that the Azure OpenAI support in the Cheshire Cat was written when the Embedder configuration was not available in the core. The choice of a specific LLM was forcing the use of a specific Embedder at the time.

The code needs a refactory.

Cristiano please test if PR #746 stops the bleeding making the web interface usable.

We can plan the work for the refactory in a new GitHub issue.

Thanks

**Comment by olafgeibig** [comment] 2024-03-12 15:48
@cristianorevil yes, when the embedder is configured the cat starts up successfully without setting the env variable.

**Comment by olafgeibig** [comment] 2024-03-12 16:17
@cristianorevil I can confirm that the problems with the vision-preview model is not a bug of the cat. I have the same issue with one of my own python scripts using langchain.

**Comment by pieroit** [comment] 2024-03-12 16:46
> The real problem is that the Azure OpenAI support in the Cheshire Cat was written when the Embedder configuration was not available in the core. The choice of a specific LLM was forcing the use of a specific Embedder at the time.
> 
> The code needs a refactory.

The Cat tries to align LLM and embedder, as soon as you set the LLM.
By removing altogether [this code](https://github.com/cheshire-cat-ai/core/blob/4c9fff02470ecd406a346652d035aa98ada71d58/core/cat/looking_glass/cheshire_cat.py#L185C9-L201C14) they can be set separately without issue (but then auto configuration of the embedder is lost).

**Comment by olafgeibig** [comment] 2024-03-12 17:01
One more thing. The reason I tried to use vision-preview is that other GPT-4 models on Azure became unbearably slow and vision-preview generates much faster. The forum at learn.microsoft.com is full of [angry complaints](https://learn.microsoft.com/en-us/answers/questions/1511386/azure-openai-service-gpt-4-is-excessively-(and-rec). One way to reduce the problem is to [limit the max_tokens](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/latency#improve-performance) (output tokens) as they often recommend in the responses. Then the generation is much faster again. Is there any way I can set this parameter?

**Comment by olafgeibig** [comment] 2024-03-12 17:06
And even one more remark. MS is retiring older OAI API version very soon, including 2023-05-15. See https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation

**Comment by valentimarco** [comment] 2024-03-12 17:39
What a mess...

**Comment by olafgeibig** [comment] 2024-03-12 17:44
@valentimarco absolutely, if this cat instance wouldn't be for my corporate employer with strict compliance requirements that ATM only Azure fulfils, I would have already ditched Azure OAI. Many devs are are really angry.

**Comment by cristianorevil** [comment] 2024-03-12 17:54
> I pushed a PR to fix partially the problem.
> 
> The real problem is that the Azure OpenAI support in the Cheshire Cat was written when the Embedder configuration was not available in the core. The choice of a specific LLM was forcing the use of a specific Embedder at the time.
> 
> The code needs a refactory.
> 
> Cristiano please test if PR #746 stops the bleeding making the web interface usable.
> 
> We can plan the work for the refactory in a new GitHub issue.
> 
> Thanks

It works. I propose to close this issue and open another with a to do list for azure, actually i have in my list:
- Upgrade packages to AzureChatOpenAI (from langchain_openai import AzureChatOpenAI)
- Add options max_tokens to bypass the slow problem with gpt-4 on azure

**Comment by olafgeibig** [comment] 2024-03-12 17:57
Closing the issue as @cristianorevil proposed. Thank you for your help!!!

**Closed** 2024-03-12 17:58 UTC
Labels: bug
